In [7]:
class Stack:
    def __init__(self, stack=None):
        if stack is None:
            self.stack = []
        else:
            self.stack = stack

    def push(self, value):
        self.stack.append(value)

    def pop(self):
        if self.isEmpty():
            return None
        return self.stack.pop()

    def top(self):
        if self.isEmpty():
            return None
        return self.stack[-1]

    def isEmpty(self):
        return len(self.stack) == 0

    def __str__(self):
        final_str = "<\n"
        for value in self.stack[::-1]:
            final_str += str(value) + "\n"
        final_str += ">"
        return final_str

    def __add__(self, other):
        if not isinstance(other, Stack):
            return Stack()

        new_stack = Stack()
        new_stack.stack = self.stack + other.stack
        return new_stack


# Create stack objects
stack1 = Stack()
stack2 = Stack()

# Push values
stack1.push(10)
stack1.push(20)
stack1.push(30)

stack2.push(40)
stack2.push(50)

print("Stack 1:")
print(stack1)

print("Stack 2:")
print(stack2)

print("Top of stack1:", stack1.top())

print("Popped from stack1:", stack1.pop())

print("Stack 1 after pop:")
print(stack1)

print("Is stack1 empty?", stack1.isEmpty())

stack3 = stack1 + stack2

print("Combined stack:")
print(stack3)

empty_stack = Stack()

print("Empty stack:")
print(empty_stack)

print("Pop from empty stack:", empty_stack.pop())
print("Top of empty stack:", empty_stack.top())
print("Is empty_stack empty?", empty_stack.isEmpty())

bad_add = stack1 + 5

print("Adding stack with non-stack object:")
print(bad_add)

Stack 1:
<
30
20
10
>
Stack 2:
<
50
40
>
Top of stack1: 30
Popped from stack1: 30
Stack 1 after pop:
<
20
10
>
Is stack1 empty? False
Combined stack:
<
50
40
20
10
>
Empty stack:
<
>
Pop from empty stack: None
Top of empty stack: None
Is empty_stack empty? True
Adding stack with non-stack object:
<
>


In [2]:
import numpy as np

# Part 1 - Convert list to NumPy array
numbers_list = [1, 2, 3, 4, 5]

array_1d = np.array(numbers_list)

print("One-dimensional array:")
print(array_1d)

# Part 2 - Create 3x3 matrix with random integers from 2 to 10
matrix = np.random.randint(2, 11, size=(3, 3))

print("\nRandom 3x3 matrix:")
print(matrix)

# Part 3 - Create Boolean matrix
# True if the number is greater than 3
boolean_matrix = matrix > 3

print("\nBoolean matrix:")
print(boolean_matrix)

One-dimensional array:
[1 2 3 4 5]

Random 3x3 matrix:
[[10 10  6]
 [ 4  5  2]
 [ 9  3  5]]

Boolean matrix:
[[ True  True  True]
 [ True  True False]
 [ True False  True]]


In [6]:
import numpy as np
import time
# from tracemalloc import start
# start()
array1 = np.array([i for i in range(2000000)])
array2 = np.array([j**2 for j in range(2000000)])
start_time = time.time()

array3 = array1 * array2
end_time = time.time()
print(end_time - start_time)

0.007375478744506836


In [8]:
file = open("hello.txt", "w+")

file.write("Hello my friend\n")
file.write("Hello world\n")
file.write("Python is fun\n")
file.write("Hello everyone\n")

file.seek(0)

text = file.read().lower()

words = text.split()

counter = 0

for word in words:
    if word == "hello":
        counter += 1

print("The word Hello appears:", counter, "times")

file.close()

The word Hello appears: 3 times
