<h3> QUESTION 1 </h3>

In [1]:
class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage


vehicle1 = Vehicle("Toyota", 180, 50000)

print(vehicle1.name)
print(vehicle1.max_speed)
print(vehicle1.mileage)

Toyota
180
50000


<h3> QUESTION 2 </h3>

In [2]:
class Bus(Vehicle):
    pass

bus1 = Bus("School Bus", 120, 30000)

print(bus1.name)
print(bus1.max_speed)
print(bus1.mileage)

School Bus
120
30000


<h3> QUESTION 3 </h3>

In [3]:
class StringClass:
    def get_String(self):
        self.text = input("Enter a string: ")

    def print_String(self):
        print(self.text.upper())


obj = StringClass()
obj.get_String()
obj.print_String()

GFJDSKSS


<h3> QUESTION 4 </h3>

In [4]:
with open("my_id.txt", "w") as file:
    file.write("name: Tomer Shimoni\n")
    file.write("age: 36\n")
    file.write("phone number: 0524722207\n")

<h3> QUESTION 5 </h3>

In [5]:

def count_words(file_path):
    word_count = {}

    with open(file_path, "r") as file:
        text = file.read()

    words = text.split()

    for word in words:
        if word in word_count:
            word_count[word] += 1
        else:
            word_count[word] = 1

    return word_count


print(count_words(r"C:\Users\tomershi\Desktop\python course\homeWork\week1 29.04-05.05\my_id.txt"))

# C:\Users\tomershi\Desktop\python course\homeWork\week1 29.04-05.05\my_id.txt

{'name:': 1, 'Tomer': 1, 'Shimoni': 1, 'age:': 1, '36': 1, 'phone': 1, 'number:': 1, '0524722207': 1}


<h3> QUESTION 6 </h3>

In [6]:
def longest_word(file_path):
    with open(file_path, "r") as file:
        text = file.read()

    words = text.split()
    longest = ""

    for word in words:
        if len(word) > len(longest):
            longest = word

    return longest


print(longest_word("my_id.txt"))

0524722207


<h3> QUESTION 7 </h3>

In [7]:
def sum_list(numbers):
    total = 0

    for num in numbers:
        total += num

    return total


print(sum_list([1, 2, 3, 4, 5]))

15


<h3> QUESTION 8 </h3>

In [8]:
def multiply_list(numbers):
    result = 1

    for num in numbers:
        result *= num

    return result


print(multiply_list([1, 2, 3, 4, 5]))

120


<h3> QUESTION 9 </h3>

In [9]:
def find_min(numbers):
    minimum = numbers[0]

    for num in numbers:
        if num < minimum:
            minimum = num

    return minimum


print(find_min([5, 2, 9, 1, 7]))

1


<h3> QUESTION 10 </h3>

In [10]:
def count_upper_lower(text):
    upper_count = 0
    lower_count = 0

    for char in text:
        if char.isupper():
            upper_count += 1
        elif char.islower():
            lower_count += 1

    return {
        "upper case": upper_count,
        "lower case": lower_count
    }


print(count_upper_lower("Alex & Sagy Are A good team"))

{'upper case': 4, 'lower case': 16}


<h3> QUESTION 11 </h3>

In [11]:
import numpy as np

arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


<h3> QUESTION 12 </h3>

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_numbers = arr[arr % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]


<h3> QUESTION 13 </h3>

In [13]:
import numpy as np

arr = np.eye(5)

arr[arr > 0] = -1

print(arr)

[[-1.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.]]


<h3> QUESTION 14 </h3>

In [14]:
def power(a, b):
    if b == 0:
        return 1

    return a * power(a, b - 1)


print(power(3, 2))

9


<h3> QUESTION 15 </h3>

In [15]:
class Stack:
    def __init__(self):
        self.items = []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        if not self.is_empty():
            return self.items.pop()
        return None

    def is_empty(self):
        return len(self.items) == 0


def is_valid_parentheses(text):
    stack = Stack()

    pairs = {
        ")": "(",
        "}": "{",
        "]": "["
    }

    opening = "({["
    closing = ")}]"

    for char in text:
        if char in opening:
            stack.push(char)

        elif char in closing:
            last_open = stack.pop()

            if last_open != pairs[char]:
                return False

    return stack.is_empty()


print(is_valid_parentheses("()"))
print(is_valid_parentheses("()[]{}"))
print(is_valid_parentheses("[)"))
print(is_valid_parentheses("({[)]"))
print(is_valid_parentheses("{{{"))

True
True
False
False
False
